version: "3.8"

services:
  bot:
    build: .
    container_name: bot
    depends_on:
      - cache
    restart: unless-stopped

    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

  cache:
    container_name: cache
    restart: unless-stopped
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - cache_data:/data
volumes:
  cache_data:
